services:
  testing:
    environment:
      - SNOWFLAKE_ACCOUNT
      - SNOWFLAKE_HOST
      - SNOWFLAKE_UID
      - SNOWFLAKE_PWD
      - SNOWFLAKE_ROLE
      - SNOWFLAKE_WH
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_TAG: 3.11-slim-buster
        REQUIREMENTS_FILE_PATH: requirements.txt
